# Generated by Django 3.0 on 2020-03-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=50, verbose_name='书名')),
                ('Book_type', models.CharField(max_length=20, verbose_name='类型')),
                ('Book_tags', models.CharField(max_length=50, verbose_name='标签')),
                ('Book_cover', models.ImageField(null=True, upload_to='', verbose_name='封面')),
                ('Book_intro', models.TextField(verbose_name='简介')),
                ('Book_manleader', models.CharField(max_length=20, verbose_name='男主')),
                ('Book_womanleader', models.CharField(max_length=30, verbose_name='女主')),
                ('Click_num', models.PositiveIntegerField(verbose_name='点击量')),
                ('Collect_num', models.PositiveIntegerField(verbose_name='收藏量')),
                ('Income', models.PositiveIntegerField(verbose_name='收入')),
                ('chapterIncome', models.PositiveIntegerField(verbose_name='章节订阅')),
                ('Git_num', models.PositiveIntegerField(verbose_name='礼物量')),
                ('recommend_num', models.PositiveIntegerField(verbose_name='推荐票量')),
                ('Book_state', models.BooleanField(verbose_name='状态')),
                ('Book_pub', models.BooleanField(verbose_name='书籍发布状态')),
                ('Book_notice', models.TextField(verbose_name='作者公告')),
                ('Book_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.CharField(max_length=10, verbose_name='验证码')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='用户账号')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=120, verbose_name='密码')),
                ('user_avatar', models.ImageField(null=True, upload_to='', verbose_name='用户头像')),
                ('user_level', models.PositiveSmallIntegerField(verbose_name='等级')),
                ('gold', models.PositiveIntegerField(verbose_name='金币')),
                ('points', models.PositiveIntegerField(verbose_name='积分')),
                ('day_ticket_num', models.PositiveIntegerField(verbose_name='推荐票数')),
                ('Wine_num', models.PositiveSmallIntegerField(verbose_name='礼物拥有量')),
                ('comment_level', models.PositiveSmallIntegerField(verbose_name='评论等级')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Aut_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Novelweb.User')),
                ('realname', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('penname', models.CharField(max_length=50, verbose_name='笔名')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('Author_info', models.TextField(verbose_name='作者信息')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_sn', models.CharField(blank=True, max_length=30, null=True, verbose_name='订单号')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', '交易支付成功'), ('TRADE_CLOSED', '未付款交易超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TEADE_FINISHED', '交易结束'), ('paying', '待支付')], max_length=40, verbose_name='支付状态')),
                ('order_mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='充值金额')),
                ('Order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novelweb.User', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.TextField(verbose_name='评论内容')),
                ('Comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('Comment_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Novelweb.Book')),
                ('Comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novelweb.User')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp', to='Novelweb.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_id', models.PositiveIntegerField(verbose_name='每本书的章节id')),
                ('Chapter_title', models.CharField(max_length=50, verbose_name='章节标题')),
                ('Chapter_text', models.TextField(verbose_name='章节内容')),
                ('Chapter_word_num', models.PositiveIntegerField(verbose_name='章节字数')),
                ('Chapter_price', models.PositiveSmallIntegerField(verbose_name='价格')),
                ('Chapter_pub', models.BooleanField(verbose_name='章节发布状态')),
                ('Chapter_time', models.DateTimeField(auto_now_add=True, verbose_name='章节时间')),
                ('Chapter_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novelweb.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Bookrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookrack_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novelweb.Book')),
                ('Bookrack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novelweb.User')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Book_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novelweb.Author'),
        ),
    ]
