# Generated by Django 3.0 on 2020-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novelweb', '0002_orderinfo_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='buy_user',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Novelweb.User', verbose_name='购买用户'),
        ),
    ]
