# Generated by Django 3.0 on 2020-03-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Novelweb', '0003_chapter_buy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='aliPay_num',
            field=models.CharField(default=123, max_length=50, verbose_name='支付宝账号'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CashoutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash_status', models.CharField(choices=[('TRADE_SUCCESS', '提现完成'), ('TRADE_WAIT', '待审核'), ('TRADE_CLOSED', '交易失败')], max_length=40, verbose_name='提现状态')),
                ('Cash_count', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='提现金额')),
                ('Cashout_time', models.DateTimeField(auto_now_add=True, verbose_name='提现时间')),
                ('Cashout_aut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novelweb.Author', verbose_name='提现人')),
            ],
        ),
    ]
