# Generated by Django 3.0 on 2020-03-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novelweb', '0004_auto_20200317_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总收入'),
        ),
    ]
